fix building with -j > 1
When combining "depend", "build" and "install" steps, openssl fails
to build in parallel mode because of races between the steps.

If "depend" and "build" are combined, the error is as follows:
    cversion.c:62:23: fatal error: buildinf.h: No such file or directory

If "build" and "install" are combined, the error is as follows:
    installing openssl
    cp: cannot stat 'openssl': No such file or directory