Fix compilation error on Ubuntu 13.10
make fails for me like this without this:

 LINK wrk
 /usr/bin/ld: deps/luajit/src/libluajit.a(lj_clib.o): undefined reference to
 /lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from co
 collect2: error: ld returned 1 exit status
 make: *** [wrk] Error 1

 $ bash --version
 GNU bash, version 4.2.45(1)-release (x86_64-pc-linux-gnu)

 $ uname -s
 Linux